<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Pritam" failures="1" tests="3" name="NegativeScenarios" time="13.333" errors="0" timestamp="2025-04-12T15:39:36 IST">
  <testcase classname="PracticeProblemsSelenium.NegativeScenarios" name="validateErrorMessageIncorrectUsernamePassword" time="1.322">
    <skipped/>
  </testcase> <!-- validateErrorMessageIncorrectUsernamePassword -->
  <testcase classname="PracticeProblemsSelenium.NegativeScenarios" name="validateErrorMessageIncorrectUsernamePassword" time="1.07">
    <skipped/>
  </testcase> <!-- validateErrorMessageIncorrectUsernamePassword -->
  <testcase classname="PracticeProblemsSelenium.NegativeScenarios" name="validateErrorMessageIncorrectUsernamePassword" time="1.1">
    <failure type="java.lang.AssertionError" message="expected [Incorrecto email or password.] but found [Incorrect email or password.]">
      <![CDATA[java.lang.AssertionError: expected [Incorrecto email or password.] but found [Incorrect email or password.]
at PracticeProblemsSelenium.NegativeScenarios.validateErrorMessageIncorrectUsernamePassword(NegativeScenarios.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- validateErrorMessageIncorrectUsernamePassword -->
</testsuite> <!-- NegativeScenarios -->
